/*
 * QubotView.java
 */

package es.pmp.qubot;

import es.pmp.qubot.conocimiento.CPregunta;
import es.pmp.qubot.control.Clic;
import es.pmp.qubot.imagenes.CPunto;
import es.pmp.qubot.imagenes.Colores;
import es.pmp.qubot.jna.Jna;
import es.pmp.qubot.imagenes.Imagenes;
import es.pmp.qubot.imagenes.Pantallas;
import es.pmp.qubot.imagenes.Regiones;
import es.pmp.qubot.tipos.CProceso;
import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

/**
 * The application's main frame.
 */
public class QubotView extends FrameView {

    public Jna jna;
    
    /** Imagen mostrada actualmente en el formulario */
    BufferedImage imagen_en_pantalla;
            
            
    
    public QubotView(SingleFrameApplication app) {
        super(app);
        initComponents();        
        jna = new Jna();
        
        this.tfTituloVentanaVysor.setText(Comun.TITULO_VENTANA_VYSOR);
        //this.getFrame().setSize(600, 400);
        
        this.tfNombreFichero.setText("22_imagenes_01.png");
        
        imagen_en_pantalla = null;
    }
    
    
    
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfTituloVentanaVysor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taProcesoVysor = new javax.swing.JTextArea();
        btnTestDetectarVysor = new javax.swing.JButton();
        btnEnviarVysorAlFrente = new javax.swing.JButton();
        btnCapturarVysor = new javax.swing.JButton();
        btnGuardarPantallaVysor = new javax.swing.JButton();
        btnCapturarVysor1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfY = new javax.swing.JTextField();
        btnTestDetectarVysor1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblCapturaVysor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombreFichero = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        tfIdentificacion = new javax.swing.JTextField();
        btnIdentificar = new javax.swing.JButton();
        btnRegiones = new javax.swing.JButton();
        lblPos = new javax.swing.JLabel();
        btnTest = new javax.swing.JButton();
        tfTest = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menuArchivo = new javax.swing.JMenu();
        miListaProcesos = new javax.swing.JMenuItem();
        javax.swing.JMenuItem miSalir = new javax.swing.JMenuItem();
        frmListaProcesos = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaProcesos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(es.pmp.qubot.QubotApp.class).getContext().getResourceMap(QubotView.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        tfTituloVentanaVysor.setText(resourceMap.getString("tfTituloVentanaVysor.text")); // NOI18N
        tfTituloVentanaVysor.setName("tfTituloVentanaVysor"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        taProcesoVysor.setEditable(false);
        taProcesoVysor.setBackground(resourceMap.getColor("taProcesoVysor.background")); // NOI18N
        taProcesoVysor.setColumns(20);
        taProcesoVysor.setFont(resourceMap.getFont("taProcesoVysor.font")); // NOI18N
        taProcesoVysor.setRows(5);
        taProcesoVysor.setName("taProcesoVysor"); // NOI18N
        jScrollPane2.setViewportView(taProcesoVysor);

        btnTestDetectarVysor.setMnemonic('T');
        btnTestDetectarVysor.setText(resourceMap.getString("btnTestDetectarVysor.text")); // NOI18N
        btnTestDetectarVysor.setName("btnTestDetectarVysor"); // NOI18N
        btnTestDetectarVysor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDetectarVysorActionPerformed(evt);
            }
        });

        btnEnviarVysorAlFrente.setMnemonic('T');
        btnEnviarVysorAlFrente.setText(resourceMap.getString("btnEnviarVysorAlFrente.text")); // NOI18N
        btnEnviarVysorAlFrente.setName("btnEnviarVysorAlFrente"); // NOI18N
        btnEnviarVysorAlFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarVysorAlFrenteActionPerformed(evt);
            }
        });

        btnCapturarVysor.setMnemonic('T');
        btnCapturarVysor.setText(resourceMap.getString("btnCapturarVysor.text")); // NOI18N
        btnCapturarVysor.setName("btnCapturarVysor"); // NOI18N
        btnCapturarVysor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarVysorActionPerformed(evt);
            }
        });

        btnGuardarPantallaVysor.setMnemonic('T');
        btnGuardarPantallaVysor.setText(resourceMap.getString("btnGuardarPantallaVysor.text")); // NOI18N
        btnGuardarPantallaVysor.setName("btnGuardarPantallaVysor"); // NOI18N
        btnGuardarPantallaVysor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPantallaVysorActionPerformed(evt);
            }
        });

        btnCapturarVysor1.setMnemonic('T');
        btnCapturarVysor1.setText(resourceMap.getString("btnCapturarVysor1.text")); // NOI18N
        btnCapturarVysor1.setName("btnCapturarVysor1"); // NOI18N
        btnCapturarVysor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarVysor1ActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        tfX.setText(resourceMap.getString("tfX.text")); // NOI18N
        tfX.setName("tfX"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        tfY.setName("tfY"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTituloVentanaVysor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTestDetectarVysor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviarVysorAlFrente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCapturarVysor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarPantallaVysor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapturarVysor1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTituloVentanaVysor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestDetectarVysor)
                    .addComponent(btnEnviarVysorAlFrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturarVysor)
                    .addComponent(btnGuardarPantallaVysor))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturarVysor1)
                    .addComponent(jLabel4)
                    .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnTestDetectarVysor1.setMnemonic('S');
        btnTestDetectarVysor1.setText(resourceMap.getString("btnTestDetectarVysor1.text")); // NOI18N
        btnTestDetectarVysor1.setToolTipText(resourceMap.getString("btnTestDetectarVysor1.toolTipText")); // NOI18N
        btnTestDetectarVysor1.setName("btnTestDetectarVysor1"); // NOI18N
        btnTestDetectarVysor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDetectarVysor1ActionPerformed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        lblCapturaVysor.setText(resourceMap.getString("lblCapturaVysor.text")); // NOI18N
        lblCapturaVysor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCapturaVysor.setName("lblCapturaVysor"); // NOI18N
        lblCapturaVysor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCapturaVysorMouseMoved(evt);
            }
        });
        jScrollPane3.setViewportView(lblCapturaVysor);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        tfNombreFichero.setText(resourceMap.getString("tfNombreFichero.text")); // NOI18N
        tfNombreFichero.setToolTipText(resourceMap.getString("tfNombreFichero.toolTipText")); // NOI18N
        tfNombreFichero.setName("tfNombreFichero"); // NOI18N

        btnCargar.setMnemonic('T');
        btnCargar.setText(resourceMap.getString("btnCargar.text")); // NOI18N
        btnCargar.setName("btnCargar"); // NOI18N
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        tfIdentificacion.setBackground(resourceMap.getColor("tfIdentificacion.background")); // NOI18N
        tfIdentificacion.setText(resourceMap.getString("tfIdentificacion.text")); // NOI18N
        tfIdentificacion.setToolTipText(resourceMap.getString("tfIdentificacion.toolTipText")); // NOI18N
        tfIdentificacion.setName("tfIdentificacion"); // NOI18N

        btnIdentificar.setMnemonic('T');
        btnIdentificar.setText(resourceMap.getString("btnIdentificar.text")); // NOI18N
        btnIdentificar.setName("btnIdentificar"); // NOI18N
        btnIdentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentificarActionPerformed(evt);
            }
        });

        btnRegiones.setMnemonic('T');
        btnRegiones.setText(resourceMap.getString("btnRegiones.text")); // NOI18N
        btnRegiones.setName("btnRegiones"); // NOI18N
        btnRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegiones))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIdentificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar)
                    .addComponent(btnRegiones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIdentificar)
                    .addComponent(tfIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblPos.setText(resourceMap.getString("lblPos.text")); // NOI18N
        lblPos.setName("lblPos"); // NOI18N

        btnTest.setText(resourceMap.getString("btnTest.text")); // NOI18N
        btnTest.setName("btnTest"); // NOI18N
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        tfTest.setBackground(resourceMap.getColor("tfTest.background")); // NOI18N
        tfTest.setToolTipText(resourceMap.getString("tfTest.toolTipText")); // NOI18N
        tfTest.setName("tfTest"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnTest)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTest, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTestDetectarVysor1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblPos))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestDetectarVysor1)
                    .addComponent(btnTest)
                    .addComponent(tfTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        menuArchivo.setMnemonic('A');
        menuArchivo.setText(resourceMap.getString("menuArchivo.text")); // NOI18N
        menuArchivo.setName("menuArchivo"); // NOI18N

        miListaProcesos.setMnemonic('p');
        miListaProcesos.setText(resourceMap.getString("miListaProcesos.text")); // NOI18N
        miListaProcesos.setName("miListaProcesos"); // NOI18N
        miListaProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaProcesosActionPerformed(evt);
            }
        });
        menuArchivo.add(miListaProcesos);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(es.pmp.qubot.QubotApp.class).getContext().getActionMap(QubotView.class, this);
        miSalir.setAction(actionMap.get("quit")); // NOI18N
        miSalir.setMnemonic('S');
        miSalir.setText(resourceMap.getString("miSalir.text")); // NOI18N
        miSalir.setName("miSalir"); // NOI18N
        menuArchivo.add(miSalir);

        menuBar.add(menuArchivo);

        frmListaProcesos.setMinimumSize(new java.awt.Dimension(1200, 900));
        frmListaProcesos.setName("frmListaProcesos"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taListaProcesos.setColumns(20);
        taListaProcesos.setFont(resourceMap.getFont("taListaProcesos.font")); // NOI18N
        taListaProcesos.setRows(5);
        taListaProcesos.setName("taListaProcesos"); // NOI18N
        jScrollPane1.setViewportView(taListaProcesos);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        btnCerrar.setMnemonic('C');
        btnCerrar.setText(resourceMap.getString("btnCerrar.text")); // NOI18N
        btnCerrar.setName("btnCerrar"); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmListaProcesosLayout = new javax.swing.GroupLayout(frmListaProcesos.getContentPane());
        frmListaProcesos.getContentPane().setLayout(frmListaProcesosLayout);
        frmListaProcesosLayout.setHorizontalGroup(
            frmListaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListaProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmListaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmListaProcesosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(frmListaProcesosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        frmListaProcesosLayout.setVerticalGroup(
            frmListaProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListaProcesosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestDetectarVysorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDetectarVysorActionPerformed
        detectarProcesoVysor();
    }//GEN-LAST:event_btnTestDetectarVysorActionPerformed

    private void btnEnviarVysorAlFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarVysorAlFrenteActionPerformed
        enviarProcesoVysorAlFrente();
    }//GEN-LAST:event_btnEnviarVysorAlFrenteActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        frmListaProcesos.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void miListaProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaProcesosActionPerformed
        verListaProcesos();
    }//GEN-LAST:event_miListaProcesosActionPerformed

    private void btnCapturarVysorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarVysorActionPerformed
        pantallaVysor2Form();
    }//GEN-LAST:event_btnCapturarVysorActionPerformed

    private void btnTestDetectarVysor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDetectarVysor1ActionPerformed
        salir();
    }//GEN-LAST:event_btnTestDetectarVysor1ActionPerformed

    private void btnGuardarPantallaVysorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPantallaVysorActionPerformed
        guardarPantallaVysor();
    }//GEN-LAST:event_btnGuardarPantallaVysorActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        cargarFicheroImagen();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnIdentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentificarActionPerformed
        identificarPantalla();
    }//GEN-LAST:event_btnIdentificarActionPerformed

    private void btnRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionesActionPerformed
        trazarRegiones();
    }//GEN-LAST:event_btnRegionesActionPerformed

    private void lblCapturaVysorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapturaVysorMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        mostrarCoordenadasSobrePantalla(x, y);
    }//GEN-LAST:event_lblCapturaVysorMouseMoved

    private void btnCapturarVysor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarVysor1ActionPerformed
        enviarClicAVysor();
    }//GEN-LAST:event_btnCapturarVysor1ActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        test();
    }//GEN-LAST:event_btnTestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturarVysor;
    private javax.swing.JButton btnCapturarVysor1;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviarVysorAlFrente;
    private javax.swing.JButton btnGuardarPantallaVysor;
    private javax.swing.JButton btnIdentificar;
    private javax.swing.JButton btnRegiones;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTestDetectarVysor;
    private javax.swing.JButton btnTestDetectarVysor1;
    private javax.swing.JFrame frmListaProcesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCapturaVysor;
    private javax.swing.JLabel lblPos;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miListaProcesos;
    private javax.swing.JTextArea taListaProcesos;
    private javax.swing.JTextArea taProcesoVysor;
    private javax.swing.JTextField tfIdentificacion;
    private javax.swing.JTextField tfNombreFichero;
    private javax.swing.JTextField tfTest;
    private javax.swing.JTextField tfTituloVentanaVysor;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    // End of variables declaration//GEN-END:variables


    
    /**
     * Muestra un mensaje de error.
     * 
     * @param mensaje                           Mensaje a mostrar
     */
    private void mostrarError(String mensaje) {
        String titulo = "Error";
        JOptionPane.showMessageDialog(this.getFrame(), mensaje, titulo, JOptionPane.ERROR_MESSAGE);
    }
    
    
    /**
     * Muestra un mensaje de error.
     * Vuelca la excepción al logger.
     * 
     * @param th                                Excepción de la que se tomará el mensaje de error
     */
    private void mostrarError(Throwable th) {
        
        Logger.getLogger(QubotView.class.getName()).log(Level.SEVERE, null, th);
        String mensaje = th.getMessage();
        mostrarError(mensaje);
    }
    
    
    /**
     * Obtiene el proceso visor.
     * 
     * @return                                  Proceso Vysor
     *                                          'null' si no se detecta
     */
    CProceso getProcesoVysor() {
        String titulo_ventana = this.tfTituloVentanaVysor.getText();
        CProceso proceso = jna.getProcesoTitulo(titulo_ventana);
        return proceso;
    }
    
    
    void verListaProcesos() {
        List <CProceso> l_procesos = this.jna.getListaProcesos();
        
        StringBuilder s = new StringBuilder();
        
        int n = 1;
        for (CProceso proceso : l_procesos) {
            
            s.append(n + ". ");
            s.append("Id: " + proceso.id_proceso + ", ");
            s.append("Handle: " + proceso.hwnd.toString() + ", ");
            s.append("Posición: (" + proceso.getPosicionS() + "), ");
            s.append("Título: " + proceso.nombre_ventana);
            s.append(Comun.NL);
            n++;
        }
        
        this.taListaProcesos.setText(s.toString());
        this.frmListaProcesos.setVisible(true);
    }

    
    /**
     * Detecta el proceso Vysor y muestra su información en pantalla.
     */
    private void detectarProcesoVysor() {
        CProceso proceso_vysor = getProcesoVysor();
        if (proceso_vysor != null) {
            String texto = proceso_vysor.toString();
            this.taProcesoVysor.setText(texto);
        } else {
            this.taProcesoVysor.setText("No se encuentra el proceso Vysor");
        }
    }

    

    /**
     * Envia el proceso Vysor al frente.
     * 
     * @param proceso_vysor                     Proceso vysor
     */
    private void enviarProcesoVysorAlFrente(CProceso proceso_vysor) {
        if (proceso_vysor != null) {
            jna.enviarAlFrente(proceso_vysor.hwnd);
        }
    }
    

    /**
     * Envia el proceso Vysor al frente.
     */
    private void enviarProcesoVysorAlFrente() {
        CProceso proceso_vysor = getProcesoVysor();
        enviarProcesoVysorAlFrente(proceso_vysor);
    }
    
    
    /**
     * Obtiene la pantalla del proceso visor.
     * 
     * La pantalla se obtiene sin escalar.
     * 
     * @return                                  Pantalla del proceso visor
     *                                          'null' si no se puede obtener
     */
    private BufferedImage capturarPantallaVysor() {
        try {
            CProceso proceso_vysor = getProcesoVysor();
            if (proceso_vysor != null) {
                jna.enviarAlFrente(proceso_vysor.hwnd);
                Thread.sleep(100);

                Rectangle rectangle = proceso_vysor.getRectangle();
                jna.getRect(proceso_vysor.hwnd);
            
                Robot robot = new Robot();
                BufferedImage img = robot.createScreenCapture(rectangle);
                return img;
            }
        
        } catch (InterruptedException | AWTException th) {
            mostrarError(th);
        }
        
        return null;
    }
    
    
    /**
     * Captura la pantalla del proceso Vysor y la muestra en el formulario.
     */
    private void pantallaVysor2Form() {
        
        CProceso proceso_vysor = getProcesoVysor();
        if (proceso_vysor != null) {

            BufferedImage img = capturarPantallaVysor();
            mostrarImagenEnForm(img);
        }
        
    }

    /**
     * Muestra una imagen en el formulario.
     * La imagen es escalada a las dimensiones adecuadas.
     * 
     * @param img                               Imagen a mostrar
     */
    private void mostrarImagenEnForm(BufferedImage img) {
        if (img == null) {
            return;
        }
        
        BufferedImage img_escala = Imagenes.escalarImagenStd(img);
        ImageIcon icon = new ImageIcon(img_escala);
        this.lblCapturaVysor.setIcon(icon);
    }
    
    
    /**
     * Guarda en disco la pantalla del proceso Vysor y la muestra en el formulario.
     */
    private void guardarPantallaVysor() {
        
        String ruta_fichero_generado = null;
        
        BufferedImage img = null;
        CProceso proceso_vysor = getProcesoVysor();
        if (proceso_vysor != null) {

            img = capturarPantallaVysor();
            String ruta_fichero = Comun.RUTA_FICHERO_CAPTURAS;
            ruta_fichero = Comun.getNombreFicheroInexistente(ruta_fichero);
            
            try {
                ruta_fichero_generado = Imagenes.guardarImagenPng(img, ruta_fichero);
                
            } catch (IOException ex) {
                mostrarError(ex);
            }
        }
        
        if (ruta_fichero_generado != null) {
            mostrarImagenEnForm(img);
            
            String titulo = "Imagen guardada";
            String mensaje = "Ruta del fichero: " + ruta_fichero_generado;
            JOptionPane.showMessageDialog(this.getFrame(), mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
        } else {
            String titulo = "Error";
            String mensaje = "No se ha podido guardar la imagen";
            JOptionPane.showMessageDialog(this.getFrame(), mensaje, titulo, JOptionPane.WARNING_MESSAGE);
        }
        
    }
    
    
    /**
     * Carga la imagen en pantalla.
     */
    private void cargarFicheroImagen() {
        String nombre_fichero = tfNombreFichero.getText();
        String ruta_fichero = Comun.RUTA_CAPTURAS + nombre_fichero;
        
        try {
            imagen_en_pantalla = Imagenes.cargarImagenPng(ruta_fichero);
        } catch (Exception ex) {
            mostrarError(ex);
        }

        if (imagen_en_pantalla != null) {
            mostrarImagenEnForm(imagen_en_pantalla);
        }
    }
    
    
    /**
     * Muestra las regiones predefinidas sobre el fichero especificado.
     */
    private void trazarRegiones() {
        if (imagen_en_pantalla != null) {
            BufferedImage imagen_regiones = Imagenes.duplicarImagen(imagen_en_pantalla);
            Regiones.trazarRegionesPregunta(imagen_regiones);
            //Regiones.trazarRegionesRevancha(imagen_regiones);
            //Regiones.trazarRegionesJugar(imagen_regiones);
            //Regiones.trazarRegionesJuegaYa(imagen_regiones);
            mostrarImagenEnForm(imagen_regiones);
        }
    }
    
    
    /**
     * Trata de identificar la imagen cargada.
     */
    private void identificarPantalla() {
        if (imagen_en_pantalla != null) {
            int tipo_pantalla = Pantallas.identificarPantalla(imagen_en_pantalla);
            String desc_tipo_pantalla = Pantallas.getDescripcionPantalla(tipo_pantalla);
            this.tfIdentificacion.setText(desc_tipo_pantalla);
        }
    }

    
    /**
     * Muestra las coordenadas relativas y absolutas del cursor sobre la imagen capturada.
     * 
     * @param x                                 Posición X del cursor relativa a la captura (0 = izquierda)
     * @param y                                 Posición Y del cursor relativa a la captura (0 = arriba)
     */
    private void mostrarCoordenadasSobrePantalla(int x, int y) {
        int ancho_captura = lblCapturaVysor.getWidth();
        int alto_captura = lblCapturaVysor.getHeight();
        
        double rel_x = 0;
        double rel_y = 0;
        if (ancho_captura > 0) {
            rel_x = (double) x * (double) 100 / (double) ancho_captura;
        }
        if (alto_captura > 0) {
            rel_y = (double) y * (double) 100 / (double) alto_captura;
        }
        
        int i_rel_x = (int) Math.round(rel_x);
        int i_rel_y = (int) Math.round(rel_y);
        String texto = "X: " + i_rel_x + ", Y: " + i_rel_y;
        this.lblPos.setText(texto);
    }


    /**
     * Envía un clic a la pantalla del vysor.
     */
    private void enviarClicAVysor() {
        
        try {
            int x = Integer.parseInt(tfX.getText());
            int y = Integer.parseInt(tfY.getText());

            CPunto punto = new CPunto(x, y);
            CProceso proceso_vysor = getProcesoVysor();
            Clic clic = new Clic();
            clic.clic(proceso_vysor, punto);
            
        } catch (Throwable th) {
            mostrarError(th);
        }

        
        // Test enviar 100 clics al azar
        /*
        try {
            CProceso proceso_vysor = getProcesoVysor();
            enviarProcesoVysorAlFrente(proceso_vysor);
            CRectangulo rect = new CRectangulo(4, 12, 96, 50);
            Clic clic = new Clic();
            
            for (int i = 0; i < 100; i++) {
                clic.clic(proceso_vysor, rect);
            }
        } catch (Throwable th) {
            mostrarError(th);
        }
        */
    }

    
    /**
     * Sale de la aplicación.
     * Solicita confirmación previa.
     */
    private void salir() {
        
        /*
        String mensaje = "¿Salir de la aplicación?";
        String titulo = "Confirmación";
        int r = JOptionPane.showConfirmDialog(this.getFrame(), mensaje, titulo, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;*/
        
        System.exit(0);
    }

    private void testDistribucionGaussiana() {
        double x0 = 0;
        double x1 = 20;
        double desviacion_tipica = (x1 - x0) / 4;
        double offset = (x1 - x0) / 2;
        
        Random r = new Random();
        
        for (int i = 0; i < 1000; i++) {
            double d = -999999;
            while (d < x0 || d > x1) {
                d = r.nextGaussian() * desviacion_tipica + x0 + offset;
            }
            
            int n = (int) Math.round(d);
            System.out.println(n);
        }
        
    }
    
    
    private void test() {
        //BufferedImage imagen_pregunta = Imagenes.extraerSubimagen(imagen_en_pantalla, Regiones.PPREG_RECT_ENUNCIADO_NORMAL);
        //BufferedImage imagen_rec = Imagenes.extraerSubimagen(imagen_en_pantalla, Regiones.PPREG_RECT_IMAGEN_ENUNCIADO_LARGA);
        BufferedImage imagen = imagen_en_pantalla;
        
        Imagenes.reemplazarColor(imagen, Colores.COLOR_VERDE_ACIERTO, Colores.COLOR_BLANCO_FONDO_PREGUNTA, 40);
        Imagenes.reemplazarColor(imagen, Colores.COLOR_ROJO_FALLO, Colores.COLOR_BLANCO_FONDO_PREGUNTA, 40);
        
        //int umbral_negro = 50;
        //Imagenes.convertirBlancoYNegro(imagen, umbral_negro);
        this.mostrarImagenEnForm(imagen);
                
        CPregunta pregunta = new CPregunta(imagen);
        String id = pregunta.getIdUnico();
        this.tfTest.setText(id);
    }
}
